config/routes.rb
# typed: strict
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # Put this at the top for ~performance~
  root 'home#index'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get 'home/index'

  resources :games do
    get :search, on: :collection
    post :add_game_to_library, on: :member
    delete :remove_game_from_library, on: :member
    delete :remove_cover, on: :member
    post :favorite, on: :member
    delete :unfavorite, on: :member
    get :favorited, on: :member
    # Path like `/games/:id/merge/:game_b_id`
    post :merge, on: :member, path: 'merge/:game_b_id'

    post :add_to_wikidata_blocklist, on: :member
  end

  resources :game_purchases, except: [:edit, :new] do
    post :bulk_update, on: :collection
  end

  resources :users do
    get :index, on: :collection
    get :search, on: :collection
    get :show, on: :member
    get :statistics, on: :member
    get :activity, on: :member
    get '/compare/:user_id...:other_user_id', as: :compare, action: :compare, on: :collection
    post :update_role, on: :member
    delete :remove_avatar, on: :member
    post :connect_steam, on: :member
    delete :disconnect_steam, on: :member
    post :steam_import, on: :member
    delete :reset_game_library, on: :member

    get :favorites, on: :member
    get :following, on: :member
    get :followers, on: :member
    post :follow, to: 'relationships#create'
    delete :unfollow, to: 'relationships#destroy'
    post :reset_token, on: :collection
    post :ban, on: :member
    post :unban, on: :member
  end

  namespace :activity do
    get :global, as: '/', path: '/'
    get :following
  end

  namespace :admin do
    get :dashboard, as: '/', path: '/'
    get :wikidata_blocklist, path: 'wikidata'
    delete :remove_from_wikidata_blocklist, path: 'wikidata/:wikidata_id/remove'

    get :new_steam_blocklist, path: 'steam/new'
    get :steam_blocklist, path: 'steam'
    post :add_to_steam_blocklist, path: 'steam'
    delete :remove_from_steam_blocklist, path: 'steam/:steam_app_id/remove'

    get :games_without_wikidata_ids

    resources :unmatched_games, param: :external_service_id, only: [:index, :destroy]
  end

  resources :events, only: :destroy

  resources :platforms do
    get :search, on: :collection
  end

  resources :engines do
    get :search, on: :collection
  end

  resources :genres do
    get :search, on: :collection
  end

  resources :companies do
    get :search, on: :collection
  end

  resources :series do
    get :search, on: :collection
  end

  resources :stores do
    get :search, on: :collection
  end

  namespace :search do
    get :index, as: '/', path: '/'
  end

  namespace :settings do
    get :profile, as: '/', path: '/'
    get :account
    get :import
    get :export
    get :export_as_json
    get :api_token, defaults: { format: :json }
  end

  scope :settings do
    # This is contributed by Doorkeeper, but Sorbet doesn't know that so we have to hack around it.
    T.unsafe(self).use_doorkeeper do
      T.unsafe(self).controllers applications: 'oauth/applications',
                                 authorized_applications: 'oauth/authorized_applications',
                                 authorizations: 'oauth/authorizations'
    end
  end

  # Implement the .well-known/change-password URL.
  get '.well-known/change-password', to: redirect('/settings/account')

  get '/about', to: 'static_pages#about'

  # For exposing the OpenSearch XML definition
  get '/opensearch', to: 'static_pages#opensearch', defaults: { format: :xml }

  # API routes
  get '/graphiql', to: 'static_pages#graphiql'
  # Execute GraphQL queries posted to '/graphql'.
  post "/graphql", to: "graphql#execute"
end

app/views/admin/_admin_header.html.erb
<div class="tabs">
  <ul>
    <li class="<%= 'is-active' if current_page?(admin_path) %>">
      <%= link_to 'Dashboard', admin_path %>
    </li>
    <li class="<%= 'is-active' if current_page?(admin_wikidata_blocklist_path) %>">
      <%= link_to 'Wikidata Blocklist', admin_wikidata_blocklist_path %>
    </li>
    <li class="<%= 'is-active' if current_page?(admin_steam_blocklist_path) %>">
      <%= link_to 'Steam Blocklist', admin_steam_blocklist_path %>
    </li>
    <li class="<%= 'is-active' if current_page?(admin_games_without_wikidata_ids_path) %>">
      <%= link_to 'Games Without Wikidata IDs', admin_games_without_wikidata_ids_path %>
    </li>
    <li class="<%= 'is-active' if current_page?(admin_unmatched_games_path) %>">
      <%= link_to 'Unmatched Games', admin_unmatched_games_path %>
    </li>
  </ul>
</div>

app/views/admin/dashboard.html.erb
<% content_for :title, "Admin Dashboard" %>

<div class="ml-50 mr-50 mr-0-mobile ml-0-mobile">
  <%= render 'admin_header' %>

  <div class="card pt-15 pb-15">
    <div class="has-text-centered has-text-weight-bold mb-25">Statistics</div>
    <%# Breaks the counts into two separate levels. %>
    <nav class="level">
      <% @counts.to_a[0...(@counts.length / 2)].each do |key, count| %>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading"><%= key.to_s.titlecase %></p>
            <p class="title"><%= count %></p>
          </div>
        </div>
      <% end %>
    </nav>

    <nav class="level">
      <% @counts.to_a[(@counts.length / 2)..@counts.length].each do |key, count| %>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading"><%= key.to_s.titlecase %></p>
            <p class="title"><%= count %></p>
          </div>
        </div>
      <% end %>
    </nav>
  </div>

  <div class="card mt-30 pt-15 pb-15">
    <div class="has-text-centered has-text-weight-bold mb-25">External Identifiers</div>
    <nav class="level">
      <% @external_id_counts.each do |key, count| %>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading"><%= key.to_s.titlecase %></p>
            <p class="title"><%= count %></p>
          </div>
        </div>
      <% end %>
    </nav>
  </div>

  <div class="card mt-30 pt-15 pb-15">
    <div class="has-text-centered has-text-weight-bold mb-25">Version Counts</div>
    <nav class="level">
      <% @version_counts.each do |key, count| %>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading"><%= key.to_s.titlecase %></p>
            <p class="title"><%= count %></p>
          </div>
        </div>
      <% end %>
    </nav>
  </div>

  <h3 class="has-text-centered mt-25 mb-10 has-text-weight-bold">Statistics Over Time</h3>
  <div class="table-container">
    <table class="table is-striped is-narrow is-bordered is-fullwidth">
      <thead>
        <tr>
          <th style="min-width: 250px;">Date</th>
          <th>Users</th>
          <th>Games</th>
          <th>Platforms</th>
          <th>Series</th>
          <th>Engines</th>
          <th>Companies</th>
          <th>Genres</th>
          <th>Stores</th>
          <th>Events</th>
          <th>Game Purchases</th>
          <th>Relationships</th>
          <th>Games with covers</th>
          <th>Games with release dates</th>
          <th>Banned users</th>
        </tr>
      </thead>
      <tbody>
        <% @statistics.each do |statistic| %>
          <tr>
            <td><%= statistic.created_at.strftime("%b %e, %Y %l:%M:%S %p") %></td>
            <td><%= statistic.users %></td>
            <td><%= statistic.games %></td>
            <td><%= statistic.platforms %></td>
            <td><%= statistic.series %></td>
            <td><%= statistic.engines %></td>
            <td><%= statistic.companies %></td>
            <td><%= statistic.genres %></td>
            <td><%= statistic.stores %></td>
            <td><%= statistic.events %></td>
            <td><%= statistic.game_purchases %></td>
            <td><%= statistic.relationships %></td>
            <td><%= statistic.games_with_covers %></td>
            <td><%= statistic.games_with_release_dates %></td>
            <td><%= statistic.banned_users %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <h3 class="has-text-centered mt-15 mb-10 has-text-weight-bold">External IDs Over Time</h3>
  <div class="table-container">
    <table class="table is-striped is-narrow is-bordered is-fullwidth">
      <thead>
        <tr>
          <th style="min-width: 250px;">Date</th>
          <th>MobyGames IDs</th>
          <th>PCGamingWiki IDs</th>
          <th>Wikidata IDs</th>
          <th>GiantBomb IDs</th>
          <th>Steam App IDs</th>
          <th>Epic Games Store IDs</th>
          <th>GOG IDs</th>
          <th>IGDB IDs</th>
        </tr>
      </thead>
      <tbody>
        <% @statistics.each do |statistic| %>
          <tr>
            <td><%= statistic.created_at.strftime("%b %e, %Y %l:%M:%S %p") %></td>
            <td><%= statistic.mobygames_ids %></td>
            <td><%= statistic.pcgamingwiki_ids %></td>
            <td><%= statistic.wikidata_ids %></td>
            <td><%= statistic.giantbomb_ids %></td>
            <td><%= statistic.steam_app_ids %></td>
            <td><%= statistic.epic_games_store_ids %></td>
            <td><%= statistic.gog_ids %></td>
            <td><%= statistic.igdb_ids %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <h3 class="has-text-centered mt-15 mb-10 has-text-weight-bold">Version Count Over Time</h3>
  <div class="table-container">
    <table class="table is-striped is-narrow is-bordered is-fullwidth">
      <thead>
        <tr>
          <th style="min-width: 250px;">Date</th>
          <th>Company Versions</th>
          <th>Game Versions</th>
          <th>Genre Versions</th>
          <th>Engine Versions</th>
          <th>Platform Versions</th>
          <th>Series Versions</th>
        </tr>
      </thead>
      <tbody>
        <% @statistics.each do |statistic| %>
          <tr>
            <td><%= statistic.created_at.strftime("%b %e, %Y %l:%M:%S %p") %></td>
            <td><%= statistic.company_versions %></td>
            <td><%= statistic.game_versions %></td>
            <td><%= statistic.genre_versions %></td>
            <td><%= statistic.engine_versions %></td>
            <td><%= statistic.platform_versions %></td>
            <td><%= statistic.series_versions %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= paginate @statistics %>
</div>

app/views/admin/games_without_wikidata_ids.html.erb
<% content_for :title, "Games Without Wikidata IDs - Admin" %>

<div class="ml-50 mr-50 mr-0-mobile ml-0-mobile">
  <%= render 'admin_header' %>

  <div class="game-card-list mt-20">
    <% @games.each do |game| %>
      <%= render 'shared/game_card', game: game %>
    <% end %>
  </div>

  <%= paginate @games %>
</div>

app/views/admin/new_steam_blocklist.html.erb
<% content_for :title, "Create a new Steam Blocklist entry - Admin" %>

<div class="ml-50 mr-50 mr-0-mobile ml-0-mobile">
  <%= render 'admin_header' %>

  <%= form_for @blocklist, url: admin_add_to_steam_blocklist_path do |f| %>
    <div class="field">
      <%= f.label :name, "Game name", class: "label" %>
      <div class="control">
        <%= f.text_field :name, value: @name, autocomplete: "off", class: "input" %>
      </div>
    </div>

    <div class="field">
      <%= f.label :steam_app_id, "Steam App ID", class: "label" %>
      <div class="control">
        <%= f.number_field :steam_app_id, value: @steam_app_id, class: "input" %>
      </div>
    </div>

    <div class="field">
      <%= f.submit "Submit", class: "button is-primary" %>
      <%= link_to("Cancel", admin_steam_blocklist_path, class: "button") %>
    </div>
  <% end %>
</div>

app/views/admin/steam_blocklist.html.erb
<% content_for :title, "Steam Blocklist - Admin" %>

<div class="ml-50 mr-50 mr-0-mobile ml-0-mobile">
  <%= render 'admin_header' %>

  <%= link_to "Create new blocklist entry", admin_new_steam_blocklist_path, class: 'button mb-10 mr-0-mobile is-fullwidth-mobile' %>

  <div class="table-container">
    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th>Steam App ID</th>
          <th>Game Name</th>
          <th>Created by</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @blocklist.each do |blocked_item| %>
          <tr>
            <th><%= link_to(blocked_item.steam_app_id, "https://store.steampowered.com/app/#{blocked_item.steam_app_id}") %></th>
            <td><%= blocked_item.name %></td>
            <td>
              <% unless blocked_item.user.nil? %>
                <%= link_to(blocked_item.user.username, blocked_item.user) %>
              <% end %>
            </td>
            <td><%= link_to "Remove", admin_remove_from_steam_blocklist_path(steam_app_id: blocked_item.steam_app_id), method: :delete, class: "is-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= paginate @blocklist %>
</div>

app/views/admin/wikidata_blocklist.html.erb
<% content_for :title, "Wikidata Blocklist - Admin" %>

<div class="ml-50 mr-50 mr-0-mobile ml-0-mobile">
  <%= render 'admin_header' %>

  <div class="table-container">
    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th>Wikidata ID</th>
          <th>Game Name</th>
          <th>Created by</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @blocklist.each do |blocked_item| %>
          <tr>
            <th><%= link_to(blocked_item.wikidata_id, "https://www.wikidata.org/wiki/Q#{blocked_item.wikidata_id}") %></th>
            <td><%= blocked_item.name %></td>
            <td>
              <% unless blocked_item.user.nil? %>
                <%= link_to(blocked_item.user.username, blocked_item.user) %>
              <% end %>
            </td>
            <td><%= link_to "Remove", admin_remove_from_wikidata_blocklist_path(wikidata_id: blocked_item.wikidata_id), method: :delete, class: "is-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= paginate @blocklist %>
</div>