config/routes.rb
# typed: strict
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # Put this at the top for ~performance~
  root 'home#index'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get 'home/index'

  resources :games do
    get :search, on: :collection
    post :add_game_to_library, on: :member
    delete :remove_game_from_library, on: :member
    delete :remove_cover, on: :member
    post :favorite, on: :member
    delete :unfavorite, on: :member
    get :favorited, on: :member
    # Path like `/games/:id/merge/:game_b_id`
    post :merge, on: :member, path: 'merge/:game_b_id'

    post :add_to_wikidata_blocklist, on: :member
  end

  resources :game_purchases, except: [:edit, :new] do
    post :bulk_update, on: :collection
  end

  resources :users do
    get :index, on: :collection
    get :search, on: :collection
    get :show, on: :member
    get :statistics, on: :member
    get :activity, on: :member
    get '/compare/:user_id...:other_user_id', as: :compare, action: :compare, on: :collection
    post :update_role, on: :member
    delete :remove_avatar, on: :member
    post :connect_steam, on: :member
    delete :disconnect_steam, on: :member
    post :steam_import, on: :member
    delete :reset_game_library, on: :member

    get :favorites, on: :member
    get :following, on: :member
    get :followers, on: :member
    post :follow, to: 'relationships#create'
    delete :unfollow, to: 'relationships#destroy'
    post :reset_token, on: :collection
    post :ban, on: :member
    post :unban, on: :member
  end

  namespace :activity do
    get :global, as: '/', path: '/'
    get :following
  end

  namespace :admin do
    get :dashboard, as: '/', path: '/'
    get :wikidata_blocklist, path: 'wikidata'
    delete :remove_from_wikidata_blocklist, path: 'wikidata/:wikidata_id/remove'

    get :new_steam_blocklist, path: 'steam/new'
    get :steam_blocklist, path: 'steam'
    post :add_to_steam_blocklist, path: 'steam'
    delete :remove_from_steam_blocklist, path: 'steam/:steam_app_id/remove'

    get :games_without_wikidata_ids

    resources :unmatched_games, param: :external_service_id, only: [:index, :destroy]
  end

  resources :events, only: :destroy

  resources :platforms do
    get :search, on: :collection
  end

  resources :engines do
    get :search, on: :collection
  end

  resources :genres do
    get :search, on: :collection
  end

  resources :companies do
    get :search, on: :collection
  end

  resources :series do
    get :search, on: :collection
  end

  resources :stores do
    get :search, on: :collection
  end

  namespace :search do
    get :index, as: '/', path: '/'
  end

  namespace :settings do
    get :profile, as: '/', path: '/'
    get :account
    get :import
    get :export
    get :export_as_json
    get :api_token, defaults: { format: :json }
  end

  scope :settings do
    # This is contributed by Doorkeeper, but Sorbet doesn't know that so we have to hack around it.
    T.unsafe(self).use_doorkeeper do
      T.unsafe(self).controllers applications: 'oauth/applications',
                                 authorized_applications: 'oauth/authorized_applications',
                                 authorizations: 'oauth/authorizations'
    end
  end

  # Implement the .well-known/change-password URL.
  get '.well-known/change-password', to: redirect('/settings/account')

  get '/about', to: 'static_pages#about'

  # For exposing the OpenSearch XML definition
  get '/opensearch', to: 'static_pages#opensearch', defaults: { format: :xml }

  # API routes
  get '/graphiql', to: 'static_pages#graphiql'
  # Execute GraphQL queries posted to '/graphql'.
  post "/graphql", to: "graphql#execute"
end

app/views/shared/_event.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <%= link_to user_path(event.user) do %>
          <%= user_avatar(event.user, size: :small) %>
        <% end %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p><%= event_text(event) %>

        <p>
          <span class="has-text-muted" title="<%= event.created_at %>">
            <%= "#{distance_of_time_in_words(event.created_at, Time.now)} ago" %>
          </span>
          <% if EventPolicy.new(current_user, event.subclass).destroy? %>
            <%= link_to event_path(event.id),
              data: { confirm: "Are you sure you want to delete this event?" },
              method: :delete, class: 'ml-5' do %>
              <%= svg_icon('trash', css_class: 'has-fill-danger-hoverable', title: 'Delete', options: { style: 'vertical-align: text-top;' }) %>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </article>
</div>

app/views/shared/_game_card.html.erb
<div class="custom-card game-card">
  <%= link_to(game_path(game.id), class: 'card-container') do %>
    <figure class="game-cover">
      <%= game_cover(game, size: :medium) %>
    </figure>
    <div class="card-content">
      <p class="title is-4 mr-10"><%= game.name %></p>
      <p class="subtitle is-6"><%= summarize(game.platforms.pluck(:name)) %></p>
      <p class="subtitle is-6"><%= summarize(game.developers.pluck(:name), limit: 2) %></p>
    </div>
  <% end %>
  <% if current_user %>
    <div data-vue-component="game-card-dropdown"
      data-vue-props="<%=
        {
          gameId: game.id,
          chevronDownIcon: svg_icon('chevron-down', height: 15, aria: false)
        }.to_json
      %>"></div>
  <% end %>
</div>

app/views/shared/_graphiql_head.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= meta_title(yield(:title)) %></title>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="64x64" href="/favicon-64.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png">
  <link rel="manifest" href="/site.webmanifest">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5856d6">
  <meta name="msapplication-TileColor" content="#5856d6">
  <meta name="theme-color" content="#5856d6">

  <meta name="description" content="<%= meta_description(yield(:description)) %>">

  <meta property="og:type" content="website">
  <meta property="og:site_name" content="vglist" />
  <meta property="og:title" content="<%= meta_title(yield(:title)) %>">
  <meta property="og:description" content="<%= meta_description(yield(:description)) %>">
  <meta property="og:url" content="<%= request.original_url %>">
  <% if yield(:opengraph_image).blank? %>
    <meta property="og:image" content="<%= asset_pack_url('media/images/vglist-opengraph-image.png')%>">
  <% else %>
    <meta property="og:image" content="<%= yield(:opengraph_image) %>">
  <% end %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <script src="<%= asset_pack_path 'media/umd/react.production.min.js' %>"></script>
  <script src="<%= asset_pack_path 'media/umd/react-dom.production.min.js' %>"></script>

  <%= stylesheet_pack_tag 'graphiql', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= meta_title(yield(:title)) %></title>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="64x64" href="/favicon-64.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png">
  <link rel="manifest" href="/site.webmanifest">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5856d6">
  <meta name="msapplication-TileColor" content="#5856d6">
  <meta name="theme-color" content="#5856d6">

  <meta name="description" content="<%= meta_description(yield(:description)) %>">

  <link href='/opensearch.xml' rel='search' title='vglist search' type='application/opensearchdescription+xml'>

  <meta property="og:type" content="website">
  <meta property="og:site_name" content="vglist" />
  <meta property="og:title" content="<%= meta_title(yield(:title)) %>">
  <meta property="og:description" content="<%= meta_description(yield(:description)) %>">
  <meta property="og:url" content="<%= request.original_url %>">
  <% if yield(:opengraph_image).blank? %>
    <meta property="og:image" content="<%= asset_pack_url('media/images/vglist-opengraph-image.png')%>">
  <% else %>
    <meta property="og:image" content="<%= yield(:opengraph_image) %>">
  <% end %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', nonce: true, 'data-turbolinks-track': 'reload' %>

  <% if Rails.env.production? %>
    <!-- Cloudflare Web Analytics -->
    <%# <%= javascript_include_tag 'https://static.cloudflareinsights.com/beacon.min.js',
        nonce: true,
        defer: true,
        data: {
          cf_beacon: { token: ENV['CLOUDFLARE_WEB_ANALYTICS_TOKEN'] }.to_json
        } %>
    <!-- End Cloudflare Web Analytics -->
  <% end %>
</head>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to(root_path, class: "navbar-item has-text-weight-semibold", title: 'vglist Home') do %>
      <%= image_pack_tag('media/images/vglist-logo.svg', width: '80px', class: 'mt-5', aria: { hidden: true }) %>
    <% end %>
    <%# Hamburger menu for mobile %>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu is-shadowless" id="navMenu">
    <div class="navbar-start">
      <%# Placeholder search input until the Vue component loads. %>
      <div class="navbar-item has-dropdown field mt-10"
        data-vue-component="search"
        data-vue-props="<%=
          {
            searchIcon: svg_icon('search', height: 16, aria: false),
            # To allow for a search param to pre-fill the input.
            searchParam: params[:search] || ''
          }.to_json
        %>"
      >
        <p class="control">
          <div class="field mb-0">
            <p class="control has-icons-left">
              <input type="search" placeholder="Search" class="input navbar-search-input">
              <span class="icon is-small is-left">
                <%= svg_icon('search', height: 16, aria: false) %>
              </span>
            </p>
          </div>
        </p>
      </div>

      <%# Link to the global activity if the user isn't logged in. %>
      <% if current_user.nil? %>
        <%= link_to("Activity", activity_path, class: "navbar-item") %>
      <% else %>
        <%= link_to("Activity", activity_following_path, class: "navbar-item") %>
      <% end %>
      <%= link_to("Games", games_path, class: "navbar-item") %>
      <%= link_to("Users", users_path, class: "navbar-item") %>
      
      <%# Include these on mobile. %>
      <%= link_to("Platforms", platforms_path, class: "navbar-item is-hidden-desktop") %>
      <%= link_to("Genres", genres_path, class: "navbar-item is-hidden-desktop") %>
      <%= link_to("Companies", companies_path, class: "navbar-item is-hidden-desktop") %>
      <%= link_to("Engines", engines_path, class: "navbar-item is-hidden-desktop") %>
      <%= link_to("Series", series_index_path, class: "navbar-item is-hidden-desktop") %>
      <%= link_to("Stores", stores_path, class: "navbar-item is-hidden-desktop") %>

      <%# Hide these behind a dropdown on desktop. %>
      <div class="navbar-item has-dropdown is-hoverable is-hidden-touch">
        <a class="navbar-link" aria-haspopup="menu" aria-controls="navbar-dropdown-more-mobile">More</a>

        <div id="navbar-dropdown-more-mobile" class="navbar-dropdown is-right">
          <%= link_to("Platforms", platforms_path, class: "navbar-item") %>
          <%= link_to("Genres", genres_path, class: "navbar-item") %>
          <%= link_to("Companies", companies_path, class: "navbar-item") %>
          <%= link_to("Engines", engines_path, class: "navbar-item") %>
          <%= link_to("Series", series_index_path, class: "navbar-item") %>
          <%= link_to("Stores", stores_path, class: "navbar-item") %>
        </div>
      </div>
    </div>

    <%# This is a bit screwy because we hide the dropdown items on mobile
        and replace them with normal items so stuff doesn't look as weird. %>
    <div class="navbar-end">
      <% if user_signed_in? %>
        <div class="navbar-item has-dropdown is-hoverable is-hidden-touch">
          <a class="navbar-link">
            <%= user_avatar(current_user, size: :small) %>
            <span class='pl-10'><%= current_user.username %></span>
          </a>

          <div class="navbar-dropdown is-right">
            <% navbar_items.each do |navbar_item| %>
              <% if navbar_item[:title].nil? %>
                <hr class="navbar-divider">
              <% elsif !navbar_item[:method].nil? %>
                <%= link_to(navbar_item[:title], navbar_item[:path], method: navbar_item[:method], class: "navbar-item") %>
              <% else %>
                <%= link_to(navbar_item[:title], navbar_item[:path], class: "navbar-item") %>
              <% end %>
            <% end %>
          </div>
        </div>

        <% navbar_items.each do |navbar_item| %>
          <% unless navbar_item[:title].nil? %>
            <% if navbar_item[:method].nil? %>
              <%= link_to(navbar_item[:title], navbar_item[:path], class: "navbar-item is-hidden-desktop") %>
            <% else %>
              <%= link_to(navbar_item[:title], navbar_item[:path], method: navbar_item[:method], class: "navbar-item is-hidden-desktop") %>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to('Sign up', new_user_registration_path, class: "navbar-item")  %>
        <%= link_to('Sign in', new_user_session_path, class: "navbar-item") %>
        <% navbar_items.each do |navbar_item| %>
          <%= link_to(navbar_item[:title], navbar_item[:path], class: "navbar-item is-hidden-desktop") %>
        <% end %>
        
        <div class="navbar-item has-dropdown is-hoverable is-hidden-touch">
          <a class="navbar-link" aria-haspopup="menu" aria-controls="navbar-dropdown-more-desktop">More</a>

          <div id="navbar-dropdown-more-desktop" class="navbar-dropdown is-right">
            <% navbar_items.each do |navbar_item| %>
              <%= link_to(navbar_item[:title], navbar_item[:path], class: "navbar-item") %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_user_card.html.erb
<div class="user-card custom-card">
  <%= link_to(user_path(user.slug), class: 'card-container') do %>
    <figure class="user-avatar">
      <%= user_avatar(user, size: :small) %>
    </figure>
    <div class="card-content">
      <p class="title is-4 mb-5 is-vertical-align-middle">
        <%= user.username %>
        <% if user.admin? %>
          <span class="tag is-primary has-text-weight-semibold ml-5">Admin</span>
        <% elsif user.moderator? %>
          <span class="tag is-primary has-text-weight-semibold ml-5">Moderator</span>
        <% end %>
        <% if user.private_account? %>
          <span class="tag is-light has-text-weight-semibold ml-5">Private</span>
        <% end %>
        <% if user.banned? %>
          <span class="tag is-danger has-text-weight-semibold ml-5">Banned</span>
        <% end %>
      </p>
      <p class="has-text-muted"><%= user.games.size %> <%= "Game".pluralize(user.games.size) %></p>
    </div>
  <% end %>
</div>